version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    image: b2c_origin:latest
    ports:
      - '3000:3000'
    environment:
      - TEST_URL=http://localhost:3000
